api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/resource/DHISCategoryCombosResource.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/resource/DHISDataElementsResource.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/resource/DHISDataSetElementResource.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/resource/DHISDataSetsResource.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/resource/DHISDataValueSetsResource.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/resource/DHISOrganisationUnitResource.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/resource/MappingResource.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/resource/PeriodIndicatorReportsResource.java
omod/src/main/webapp/resources/dhisconnector.js
omod/src/main/webapp/resources/manage-mappings.js

See https://issues.openmrs.org/browse/DCM-1
- URL Encoded the DHIS2 API requests
- URL Encoded UI API calls
- Replace "2.0.*" with "2.*" in supported OpenMRS versions of endpoints
- Fix disabled field issue in the duplicate mapping view

DCM-1: Make the core functionalities work

---

omod/src/main/webapp/resources/dhisconnector.js

See https://issues.openmrs.org/browse/DCM-6
- Change `Mapped Category` to `Mapped Category Option Combination`
- Change `Data Element Options`  to `Data Elements`
- Change `Category Options`  to `Category Option Combinations`

DCM-6: Fix typos in the Mapping UI

---

.travis.yml

- See https://issues.openmrs.org/browse/DCM-10
- Create the travis.yml file

DCM-10: Configure Travis CI for the project

---

api/pom.xml
omod/pom.xml
pom.xml

See https://issues.openmrs.org/browse/DCM-25
- Change `reportingVersion version ` to 1.20.0
- Change `calculationVersion version ` to 1.2`

DCM-25: Update module requirement versions

---

pom.xml

See https://issues.openmrs.org/browse/DCM-26
- Change `reportingVersion version ` to 1.20.0
- Change `calculationVersion version ` to 1.2`

DCM-26: Update module requirement versions

---

omod/src/main/webapp/resources/dhisconnector-runreports.js

See https://issues.openmrs.org/browse/DCM-28
- Replace the values of the mappings selector's options with mapping index
- Introduce a global variable to keep the selected mapping
- Replace existing period type extraction logic with the introduced selectedMapping variable.

 DCM:28: Map indicator mappings using index in Run Report view

---

api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java

See [https://issues.openmrs.org/browse/DCM-22](https://issues.openmrs.org/browse/DCM-22) 
Add Financial July period type support for automation by updating the following method:
```src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java:transformToDHISPeriod```

DCM-22: Support Financial July period type in automation

---

omod/src/main/webapp/resources/dhisconnector-runreports.js
omod/src/main/webapp/runReports.jsp

See https://issues.openmrs.org/browse/DCM-29
Add a generalised year picker for Financial years

DCM-29: Implement a generalised financial picker in Run Report

---

omod/src/main/webapp/resources/dhisconnector-runreports.js
omod/src/main/webapp/runReports.jsp

See https://issues.openmrs.org/projects/DCM/issues/DCM-15?filter=allopenissues
Create a six monthly picker in run report

DCM-15: Create a six monthly picker in run report

---

omod/src/main/webapp/resources/dhisconnector-runreports.js
omod/src/main/webapp/runReports.jsp

[[DCM - 19] Support Six-monthly April period type](https://issues.openmrs.org/browse/DCM-19)
The issue had two parts listed under it,
1. Update the backend
2. Update the date picker in the run reports 
The first part had already implemented with the issue DCM-32, so this PR contains the second part of the issue. 
* Created two html elements, an `input` for `sixMonthlyAprilPicker` and a `select` for `sixMonthAprilTypeSelector`
* Created a function to initialize the six monthly april picker
* Create a function to handle changes in the above html elements

DCM-19: Create six month april picker in run reports

---

README.md

See https://issues.openmrs.org/browse/DCM-34
Added automation instructions to `README.md` 
Updated todo and implemented lists in `README.md`
Updated outdated links

DCM-34: Add the missing details to README.md

---

api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java

See [https://issues.openmrs.org/browse/DCM-41](https://issues.openmrs.org/browse/DCM-41) 
Added the BiMonthly period support to automation

DCM-41: Support BiMonthly period type in Automation

---

api/src/main/java/org/openmrs/module/dhisconnector/DHISPeriodTypeUnit.java
api/src/main/java/org/openmrs/module/dhisconnector/ReportToDataSetMapping.java
api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
api/src/test/java/org/openmrs/module/dhisconnector/adx/PostAdxTest.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java

See [https://issues.openmrs.org/browse/DCM-40](https://issues.openmrs.org/browse/DCM-40) 
Added the BiWeekly period support to automation

DCM-40: Support BiWeekly period type in Automation

---

api/src/main/java/org/openmrs/module/dhisconnector/api/DHISConnectorService.java
api/src/main/java/org/openmrs/module/dhisconnector/api/db/DHISConnectorDAO.java
api/src/main/java/org/openmrs/module/dhisconnector/api/db/hibernate/HibernateDHISConnectorDAO.java
api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
api/src/test/java/org/openmrs/module/dhisconnector/api/DHISConnectorServiceTest.java
api/src/test/resources/test-hibernate.cfg.xml
omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
omod/src/main/webapp/locationMapping.jsp
omod/src/main/webapp/resources/dhisconnector-locationmapping.js

See [https://issues.openmrs.org/browse/DCM-48](https://issues.openmrs.org/browse/DCM-48) 
Add Saving/Updating feature to the location mapping page

DCM-48: Add save/update functionality to location mapping UI

---

api/src/main/java/org/openmrs/module/dhisconnector/DHISPeriodTypeUnit.java
api/src/main/java/org/openmrs/module/dhisconnector/ReportToDataSetMapping.java
api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
api/src/test/java/org/openmrs/module/dhisconnector/api/DHISConnectorServiceTest.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java

See [https://issues.openmrs.org/browse/DCM-39](https://issues.openmrs.org/browse/DCM-39) 
Added Weekly sunday period support to automation
Fixed a bug in weekly period support

DCM-39: Support Weekly Sunday period type in Automation

---

api/src/main/java/org/openmrs/module/dhisconnector/DHISPeriodTypeUnit.java
api/src/main/java/org/openmrs/module/dhisconnector/ReportToDataSetMapping.java
api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
api/src/test/java/org/openmrs/module/dhisconnector/api/DHISConnectorServiceTest.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java

See [https://issues.openmrs.org/browse/DCM-44](https://issues.openmrs.org/browse/DCM-44) 
Added Weekly Wednesday period support to automation

DCM-44: Support Weekly Wednesday period type in Automation

---

api/src/main/java/org/openmrs/module/dhisconnector/DHISPeriodTypeUnit.java
api/src/main/java/org/openmrs/module/dhisconnector/ReportToDataSetMapping.java
api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
api/src/test/java/org/openmrs/module/dhisconnector/api/DHISConnectorServiceTest.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java

See [https://issues.openmrs.org/browse/DCM-45](https://issues.openmrs.org/browse/DCM-45) 
Added Weekly Thursday period support to automation

DCM-45: Support Weekly Thursday period type in Automation

---

api/src/main/java/org/openmrs/module/dhisconnector/DHISPeriodTypeUnit.java
api/src/main/java/org/openmrs/module/dhisconnector/ReportToDataSetMapping.java
api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
api/src/test/java/org/openmrs/module/dhisconnector/api/DHISConnectorServiceTest.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java

See [https://issues.openmrs.org/browse/DCM-46](https://issues.openmrs.org/browse/DCM-46) 
Added Weekly Saturday period support to automation

DCM-46: Support Weekly Saturday period type in Automation

---

api/src/main/java/org/openmrs/module/dhisconnector/api/DHISConnectorService.java
api/src/main/java/org/openmrs/module/dhisconnector/api/db/DHISConnectorDAO.java
api/src/main/java/org/openmrs/module/dhisconnector/api/db/hibernate/HibernateDHISConnectorDAO.java
api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
api/src/test/java/org/openmrs/module/dhisconnector/api/DHISConnectorServiceTest.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/resource/DHISDataSetsResource.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/resource/LocationMappingResource.java
omod/src/main/webapp/locationMapping.jsp
omod/src/main/webapp/resources/dhisconnector-locationmapping.js
omod/src/main/webapp/resources/dhisconnector-runreports.js
omod/src/main/webapp/runReports.jsp

See [https://issues.openmrs.org/browse/DCM-49](https://issues.openmrs.org/browse/DCM-49) 
Upgraded the Run Reports Functionality to work with automated location mappings
Fixed a bug in location mapping UI

DCM-49: Add automated location mapping for Run Reports UI

---

api/src/main/java/org/openmrs/module/dhisconnector/ReportToDataSetMapping.java
api/src/main/java/org/openmrs/module/dhisconnector/api/DHISConnectorService.java
api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
api/src/main/resources/liquibase.xml
omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
omod/src/main/webapp/automation.jsp

See [https://issues.openmrs.org/browse/DCM-50](https://issues.openmrs.org/browse/DCM-50) 
Upgraded the Automation(Scheduling) Functionality to work with automated location mappings
https://vimeo.com/578453879

DCM-50: Add automated location mapping for Automation UI

---

api/src/main/java/org/openmrs/module/dhisconnector/DHISPeriodTypeUnit.java
api/src/main/java/org/openmrs/module/dhisconnector/ReportToDataSetMapping.java
api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
api/src/test/java/org/openmrs/module/dhisconnector/api/DHISConnectorServiceTest.java

See [https://issues.openmrs.org/browse/DCM-42](https://issues.openmrs.org/browse/DCM-42) 
Added Financial November period support to automation

DCM-42: Support Financial November period type in Automation

---

omod/src/main/resources/config.xml

See [https://issues.openmrs.org/browse/DCM-53](https://issues.openmrs.org/browse/DCM-53) 
Created the set of module privileges

DCM-53: Create user privileges for the module

---

api/src/main/java/org/openmrs/module/dhisconnector/api/DHISConnectorService.java
api/src/main/java/org/openmrs/module/dhisconnector/api/db/DHISConnectorDAO.java
api/src/main/java/org/openmrs/module/dhisconnector/api/db/hibernate/HibernateDHISConnectorDAO.java
api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
api/src/main/java/org/openmrs/module/dhisconnector/api/util/DHISConnectorUtil.java
api/src/test/java/org/openmrs/module/dhisconnector/api/DHISConnectorServiceTest.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java

fix the ticket [[DCM-61] Implement import DHIS mappings with metadata feature](https://issues.openmrs.org/browse/DCM-61)
Update the upload mappings function to import metadata files as well
Write unit tests to test mapping sharing
- Java 8 Oracle
- Maven 3.6.3
- OpenMRS Reference Application 2.11.0
- MySQL server
- macOS bigSur

DCM 61: Implement import DHIS mappings with metadata function

---

omod/src/main/webapp/createMapping.jsp
omod/src/main/webapp/manageMappings.jsp
omod/src/main/webapp/resources/dhisconnector.js

See [https://issues.openmrs.org/browse/DCM-57](https://issues.openmrs.org/browse/DCM-57) 
Updated the Create and Manage Mappings UI to behave according to the user privileges
https://talk.openmrs.org/t/dhis-connector-module-user-access-controlling/34059/11?u=piumal1999

DCM-57: Add user privileges to Create and Manage Mappings UI

---

omod/src/main/webapp/configureServer.jsp
omod/src/main/webapp/template/localHeader.jsp

See [https://issues.openmrs.org/browse/DCM-54](https://issues.openmrs.org/browse/DCM-54) 
Updated the Configure DHIS Connection UI to behave according to the user privileges
https://talk.openmrs.org/t/dhis-connector-module-user-access-controlling/34059/10?u=piumal1999

DCM-54: Add user privileges to Configure DHIS Connection UI

---

README.md

See [https://issues.openmrs.org/browse/DCM-66](https://issues.openmrs.org/browse/DCM-65) 
Updated the README.md file with new feature content

DCM-65: Update the README.md with new feature details

---

README.md

See [https://issues.openmrs.org/browse/DCM-68](https://issues.openmrs.org/browse/DCM-68) 
Added the missing details to readme.md file

DCM-68: Add automation details to the README.md

---

omod/src/main/java/org/openmrs/module/dhisconnector/extension/html/AdminList.java
omod/src/main/java/org/openmrs/module/dhisconnector/web/bean/DynamicBeanConfiguration.java
omod/src/main/resources/webModuleApplicationContext.xml
omod/src/main/webapp/automation.jsp
omod/src/main/webapp/configureServer.jsp
omod/src/main/webapp/createMapping.jsp
omod/src/main/webapp/failedData.jsp
omod/src/main/webapp/locationMapping.jsp
omod/src/main/webapp/manageMappings.jsp
omod/src/main/webapp/runReports.jsp
omod/src/main/webapp/template/localHeader.jsp

See [https://issues.openmrs.org/browse/DCM-81](https://issues.openmrs.org/browse/DCM-81) 
Removed the [deprecated](https://docs.spring.io/spring-framework/docs/4.3.7.RELEASE_to_4.3.8.RELEASE/Spring%20Framework%204.3.8.RELEASE/org/springframework/web/servlet/mvc/annotation/DefaultAnnotationHandlerMapping.html) bean (`DefaultAnnotationHandlerMapping`) and added the dynamic bean handling configuration.
Fixed the broken paths

DCM-81: Fix broken paths and dependencies
