openmrs/openmrs-module-dhisconnector

omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java, omod/src/main/webapp/configureServer.jsp
See https://issues.openmrs.org/browse/DCM-5
Add the placeholder for the input
Remove the password value
Remove the password attribute from the backend
=> DCM-5: Hide the existing password from the UI

api/pom.xml
See [https://issues.openmrs.org/browse/DCM-27](https://issues.openmrs.org/browse/DCM-27) 
Update `httpcore` version from 4.2.1 to 4.4.13 in `/api/pom.xml`
Update `httpclient` version from 4.3.6 to 4.5.12 in `/api/pom.xml`
=> DCM-27: Bump httpclient and httpcore versions

api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
See [https://issues.openmrs.org/browse/DCM-20](https://issues.openmrs.org/browse/DCM-20) 
Add Yearly period type support for automation by updating the following method:
```src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java:transformToDHISPeriod```
=> DCM-20: Support Yearly period type in automation

api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
See [https://issues.openmrs.org/browse/DCM-21](https://issues.openmrs.org/browse/DCM-21) 
Add Financial April period type support for automation by updating the following method:
```src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java:transformToDHISPeriod```
=> DCM-21: Support Financial April period type in automation

api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
See [https://issues.openmrs.org/browse/DCM-23](https://issues.openmrs.org/browse/DCM-23) 
Add Financial October period type support for automation by updating the following method:
```src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java:transformToDHISPeriod```
=> DCM-23: Support Financial October period type in automation

api/src/main/resources/messages.properties, omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java, omod/src/main/webapp/automation.jsp
See https://issues.openmrs.org/browse/DCM-24
Add an if condition to check the period types
I have used the period type as the name of the mapping when testing :
=> DCM-24: Remove unsupported mappings from automation view

api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java, omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
See [https://issues.openmrs.org/browse/DCM-31](https://issues.openmrs.org/browse/DCM-31) 
Added SixMonthly period type support for automation by updating the following method:
```src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java:transformToDHISPeriod```
Added SixMonthly as to supported period types array.
=> DCM-31: Support SixMonthly period type in automation

api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java, omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
See [https://issues.openmrs.org/browse/DCM-32](https://issues.openmrs.org/browse/DCM-32) 
Added SixMonthly April period type support for automation by updating the following method:
```src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java:transformToDHISPeriod```
Added SixMonthly April to supported period types array.
=> DCM-32: Support SixMonthly April period type in automation

api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java, omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
[DCM-33 Support Quarterly Period Type in Automation](https://issues.openmrs.org/browse/DCM-33)
* Updated the function `src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java:transformToDHISPeriod`
* Appended another `else if` block to the existing `if else` to catch the `Quarterly Type`
* Compared the current start date with the quarterly boundary dates to find the correct quarter.
* Created a function to get the quarter number for a given date.
* Configured it to return a period in the format of `yyyyQn` where n is the quarter number.
=> DCM-33 - Support Quarterly Period Type in Automation

omod/src/main/webapp/resources/dhisconnector-runreports.js, omod/src/main/webapp/runReports.jsp
[DCM-14: Support quarterly period type in run reports](https://issues.openmrs.org/browse/DCM-14)
* Extended the switch case in the run reports `js` file to catch the period type quarterly
* Created a new function to initialize the quarterly year picker and quarter selector
* Created a new function to handle the changes of the above two elements
=> DCM-14: Create quarterly picker in run reports

api/src/main/resources/liquibase.xml
See [https://issues.openmrs.org/browse/DCM-38](https://issues.openmrs.org/browse/DCM-38) 
Update the `liquibase.xml` to generate a table to store the location mappings(OMRS locations and DHIS2 organizationUnits).
The table contains these fields: id, uuid, creator, date_created, org_unit_uid, location
=> DCM-38: Generate the tables required for location mapping feature

api/src/main/java/org/openmrs/module/dhisconnector/LocationToOrgUnitMapping.java, api/src/main/java/org/openmrs/module/dhisconnector/api/DHISConnectorService.java, api/src/main/java/org/openmrs/module/dhisconnector/api/db/DHISConnectorDAO.java, api/src/main/java/org/openmrs/module/dhisconnector/api/db/hibernate/HibernateDHISConnectorDAO.java, api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java, api/src/main/resources/messages.properties, omod/src/main/java/org/openmrs/module/dhisconnector/extension/html/AdminList.java, omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java, omod/src/main/webapp/locationMapping.jsp, omod/src/main/webapp/template/localHeader.jsp
See [https://issues.openmrs.org/browse/DCM-47](https://issues.openmrs.org/browse/DCM-47) 
Created the User interface of location mapping
This UI displays the mapped location-orgUnits which are saved in the database
Note- Saving/Updating feature will be added under a new JIRA issue
=> DCM-47: Initiate the location mapping user interface

api/pom.xml, api/src/main/java/org/openmrs/module/dhisconnector/api/DHISConnectorService.java, api/src/main/java/org/openmrs/module/dhisconnector/api/db/DHISConnectorDAO.java, api/src/main/java/org/openmrs/module/dhisconnector/api/db/hibernate/HibernateDHISConnectorDAO.java, api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java, api/src/main/java/org/openmrs/module/dhisconnector/api/util/DHISConnectorUtil.java, api/src/test/java/org/openmrs/module/dhisconnector/api/DHISConnectorServiceTest.java, omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java, pom.xml
fix the ticket [[DCM-59] Implement export DHIS mapping files with the underlying metadata feature](https://issues.openmrs.org/browse/DCM-59)
Include related metadata as XML files into the export bundle
Write unit tests to test mapping sharing
Create a new file to keep utility functions of the DHISService file
- Java 8 Oracle
- Maven 3.6.3
- OpenMRS Reference Application 2.11.0
- MySQL server
- macOS bigSur
=> DCM 59: Implement export DHIS mappings with underlying metadata feature

omod/src/main/webapp/locationMapping.jsp, omod/src/main/webapp/template/localHeader.jsp
See [https://issues.openmrs.org/browse/DCM-56](https://issues.openmrs.org/browse/DCM-56) 
Updated the Location Mapping UI to behave according to the user privileges
https://talk.openmrs.org/t/dhis-connector-module-user-access-controlling/34059/5?u=piumal1999
=> DCM-56: Add user privileges to Location Mapping UI

omod/src/main/resources/config.xml, omod/src/main/webapp/automation.jsp, omod/src/main/webapp/failedData.jsp, omod/src/main/webapp/runReports.jsp, omod/src/main/webapp/template/localHeader.jsp
See [https://issues.openmrs.org/browse/DCM-55](https://issues.openmrs.org/browse/DCM-55) 
Updated the Automation UI and Run Reports UIs to behave according to the user privileges
https://talk.openmrs.org/t/dhis-connector-module-user-access-controlling/34059/8?u=piumal1999
=> DCM-55: Add user privileges to Automation UI and Run Reports UI

api/src/main/java/org/openmrs/module/dhisconnector/api/DHISConnectorService.java, api/src/main/java/org/openmrs/module/dhisconnector/api/db/DHISConnectorDAO.java, api/src/main/java/org/openmrs/module/dhisconnector/api/db/hibernate/HibernateDHISConnectorDAO.java, api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java, api/src/main/resources/messages.properties, api/src/test/java/org/openmrs/module/dhisconnector/api/DHISConnectorServiceTest.java, omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java, omod/src/main/webapp/manageMappings.jsp
fix the ticket [[DCM-64] Improve the import mappings function to include override metadata option](https://issues.openmrs.org/browse/DCM-64)
- Change the form to have a checkbox to check if the metadata needs to be overridden
- Catch the value from the controller and modify the service function to get a boolean as a parameter 
- Check for the parameter value and if true replace the existing otherwise ignore
https://user-images.githubusercontent.com/45477334/129008380-556ce474-357e-4056-92de-8552c408b3cc.mov
- Java 8 Oracle
- Maven 3.6.3
- OpenMRS Reference Application 2.11.0
- MySQL server
- macOS bigSur
=> DCM-64: Improve the import mappings function to include override metadata option

api/src/main/java/org/openmrs/module/dhisconnector/api/DHISConnectorService.java, api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java, api/src/test/java/org/openmrs/module/dhisconnector/api/DHISConnectorServiceTest.java, omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java, omod/src/main/webapp/manageMappings.jsp, omod/src/main/webapp/resources/dhisconnector.css
fix the ticket [[DCM-63] Improve the export mappings function to let users pick metadata export](https://issues.openmrs.org/browse/DCM-63)
- Change the form to have a checkbox to pick if the metadata are not required 
- Catch the value from the controller and modify the service function to get a boolean as a parameter 
- Check for the parameter value before adding the metadata into the bundle
https://user-images.githubusercontent.com/45477334/128591305-a4f60d05-8f30-4902-a31e-7650c2bdf3a3.mov
- Java 8 Oracle
- Maven 3.6.3
- OpenMRS Reference Application 2.11.0
- MySQL server
- macOS bigSur
=> DCM 63: Improve the export mappings function to let users pick metadata export

api/src/main/java/org/openmrs/module/dhisconnector/Configurations.java, omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java, omod/src/main/webapp/automation.jsp
See [https://issues.openmrs.org/browse/DCM-7](https://issues.openmrs.org/browse/DCM-7) 
Made the enable automation option of automation page a separate option. So the users have a separate button to toggle automation
https://vimeo.com/584612376
=> DCM-7: Make the enable automation option a separate option

api/src/main/java/org/openmrs/module/dhisconnector/api/impl/DHISConnectorServiceImpl.java
See: https://issues.openmrs.org/browse/DCM-70
* Replace all `println` commands with loggers.
=> DCM-70: Use loggers instead of println commands in dhis connector service

omod/src/main/webapp/resources/dhisconnector.css, omod/src/main/webapp/runReports.jsp
See: [DCM-73 Run Report UI is getting cluttered after pushing data](https://issues.openmrs.org/browse/DCM-73)
Fixed the issues where UI gets cluttered after multiple organization responses are displayed.
=> DCM-73: Improve Run Report UI getting cluttered after pushing data
